import { describe, expect, test } from 'bun:test'
import {
  NvidiaNimTaskTool,
  resolveNvidiaTaskModel,
} from '../src/tools/NvidiaNimTaskTool/NvidiaNimTaskTool.js'

describe('NVIDIA one-shot tool contract', () => {
  test('resolves an explicit or selected task before inferring a default', () => {
    expect(
      resolveNvidiaTaskModel(
        { model: 'google/paligemma', prompt: 'Describe it', image_path: 'a.png' },
        'stabilityai/stable-video-diffusion',
      ),
    ).toBe('google/paligemma')
    expect(
      resolveNvidiaTaskModel(
        { prompt: 'A product photograph' },
        'black-forest-labs/flux.1-schnell',
      ),
    ).toBe('black-forest-labs/flux.1-schnell')
  })

  test('infers only implemented task adapters from the requested media shape', () => {
    expect(resolveNvidiaTaskModel({ prompt: 'A landscape' }, undefined)).toBe(
      'black-forest-labs/flux.1-schnell',
    )
    expect(resolveNvidiaTaskModel({ image_path: 'source.jpg' }, undefined)).toBe(
      'stabilityai/stable-video-diffusion',
    )
    expect(
      resolveNvidiaTaskModel(
        { image_path: 'source.png', prompt: 'What is shown?' },
        undefined,
      ),
    ).toBe('google/paligemma')
  })

  test('keeps generated bytes out of provider-facing tool results', () => {
    const block = NvidiaNimTaskTool.mapToolResultToToolResultBlockParam(
      {
        model: 'black-forest-labs/flux.1-schnell',
        taskKind: 'text-to-image',
        purpose: 'Generate one image.',
        outputPath: '/tmp/generated.jpg',
        mediaType: 'image/jpeg',
        seed: 7,
      },
      'tool-1',
    )

    expect(block).toEqual({
      type: 'tool_result',
      tool_use_id: 'tool-1',
      content:
        'NVIDIA text-to-image completed with black-forest-labs/flux.1-schnell. Artifact saved to /tmp/generated.jpg (seed 7).',
    })
    expect(JSON.stringify(block)).not.toContain('base64')
    expect(JSON.stringify(block)).not.toContain('image_url')
  })
})
