import { describe, expect, test } from 'bun:test'
import {
  NvidiaSpecialTool,
  resolveNvidiaTaskModel,
} from '../src/tools/NvidiaNimTaskTool/NvidiaNimTaskTool.js'

describe('NVIDIA one-shot tool contract', () => {
  test('resolves an explicit or selected task before inferring a default', () => {
    expect(
      resolveNvidiaTaskModel(
        { model: 'google/paligemma', prompt: 'Describe it', image_path: 'a.png' },
        'nvidia/bnr',
      ),
    ).toBe('google/paligemma')
    expect(
      resolveNvidiaTaskModel(
        { prompt: 'A product photograph' },
        'nvidia/cosmos3-nano',
      ),
    ).toBe('nvidia/cosmos3-nano')
  })

  test('infers a generated task contract from the requested media shape', () => {
    expect(resolveNvidiaTaskModel({ prompt: 'A landscape' }, undefined)).toBe(
      'google/diffusiongemma-26b-a4b-it',
    )
    expect(resolveNvidiaTaskModel({ image_path: 'source.jpg' }, undefined)).toBe(
      'google/paligemma',
    )
    expect(
      resolveNvidiaTaskModel(
        { image_path: 'source.png', prompt: 'What is shown?' },
        undefined,
      ),
    ).toBe('google/paligemma')
    expect(resolveNvidiaTaskModel({ video_path: 'source.mp4' }, undefined)).toBe(
      'nvidia/synthetic-video-detector',
    )
    expect(resolveNvidiaTaskModel({ audio_path: 'source.wav' }, undefined)).toBe(
      'nvidia/bnr',
    )
  })

  test('keeps generated bytes out of provider-facing tool results', () => {
    expect(NvidiaSpecialTool.name).toBe('NvidiaSpecial')
    const block = NvidiaSpecialTool.mapToolResultToToolResultBlockParam(
      {
        model: 'nvidia/cosmos3-nano',
        taskKind: 'video-generation',
        purpose: 'Generate a physics-aware video.',
        outputPath: '/tmp/generated.mp4',
        mediaType: 'video/mp4',
        seed: 7,
      },
      'tool-1',
    )

    expect(block).toEqual({
      type: 'tool_result',
      tool_use_id: 'tool-1',
      content:
        'NVIDIA video-generation completed with nvidia/cosmos3-nano. Artifact saved to /tmp/generated.mp4 (seed 7).',
    })
    expect(JSON.stringify(block)).not.toContain('base64')
    expect(JSON.stringify(block)).not.toContain('image_url')
  })
})
