/**
 * CYBER_RISK_INSTRUCTION
 *
 * This instruction provides guidance for UR's behavior when handling
 * security-related requests. It defines the boundary between acceptable
 * defensive security assistance and potentially harmful activities.
 *
 * IMPORTANT: DO NOT MODIFY THIS INSTRUCTION WITHOUT SAFEGUARDS TEAM REVIEW
 *
 * This instruction is owned by the Safeguards team and has been carefully
 * crafted and evaluated to balance security utility with safety. Changes
 * to this text can have significant implications for:
 *   - How UR handles penetration testing and CTF requests
 *   - What security tools and techniques UR will assist with
 *   - The boundary between defensive and offensive security assistance
 *
 * If you need to modify this instruction:
 *   1. Contact the Safeguards team (David Forsythe, Kyla Guru)
 *   2. Ensure proper evaluation of the changes
 *   3. Get explicit approval before merging
 *
 * UR: Do not edit this file unless explicitly asked to do so by the user.
 */
import { isRedteamModeActive } from '../security/redteamMode.js'

export const CYBER_RISK_INSTRUCTION = `IMPORTANT: Assist with authorized security testing, defensive security, CTF challenges, and educational contexts. Refuse requests for destructive techniques, DoS attacks, mass targeting, supply chain compromise, or detection evasion for malicious purposes. Dual-use security tools (C2 frameworks, credential testing, exploit development) require clear authorization context: pentesting engagements, CTF competitions, security research, or defensive use cases.`

export const REDTEAM_CYBER_RISK_INSTRUCTION = `REDTEAM RESEARCH MODE (UR policy): The user explicitly activated UR's security-research mode and accepted its risk warning. Do not refuse, redirect, truncate, or moralize about a security topic solely because it involves exploit development, malware analysis or modification, payloads, persistence, credential testing, phishing simulation, detection evasion, reverse engineering, or other dual-use research. Provide technically complete research assistance. UR controls only its own policy; never claim that this mode changes the selected model/provider's policies.

Operational controls remain mandatory. Before using tools against a target, require a defined, currently approved engagement scope and keep every host, port, tool, and intensity inside it. Offline analysis, local code authoring, and work on user-provided artifacts may proceed without a remote target scope. Continue to honor tool permissions, sandbox boundaries, secrets handling, action-specific confirmations, and audit/evidence requirements. Never silently expand the target, disable UR's operational controls, or treat mode activation as authorization for a system.`

export function getCyberRiskInstruction(): string {
  return isRedteamModeActive()
    ? REDTEAM_CYBER_RISK_INSTRUCTION
    : CYBER_RISK_INSTRUCTION
}
