import { getInitialSettings } from '../utils/settings/settings.js'

export function getSpinnerVerbs(): string[] {
  const settings = getInitialSettings()
  const config = settings.spinnerVerbs
  if (!config) {
    return SPINNER_VERBS
  }
  if (config.mode === 'replace') {
    return config.verbs.length > 0 ? config.verbs : SPINNER_VERBS
  }
  return [...SPINNER_VERBS, ...config.verbs]
}

// Spinner verbs for loading messages.
// Themed for UR — the ancient Sumerian city: the Ziggurat, the Mashoof reed
// canoe, the Ahwar marshes, lapis-lazuli & gold of the Standard of Ur, and
// cuneiform pressed into clay. Single-word gerunds (like the originals) so the
// spinner reads "Verb…" and never overflows the line. Extend or replace via the
// `spinnerVerbs` setting.
export const SPINNER_VERBS = [
  'Alloying',
  'Annealing',
  'Annotating',
  'Anointing',
  'Auguring',
  'Baking',
  'Bartering',
  'Beading',
  'Beseeching',
  'Bituminizing',
  'Bobbing',
  'Bricklaying',
  'Brewing',
  'Bundling',
  'Burnishing',
  'Buttressing',
  'Calculating',
  'Calendaring',
  'Caravanning',
  'Carding',
  'Casting',
  'Censing',
  'Channeling',
  'Charting',
  'Cogitating',
  'Computing',
  'Consecrating',
  'Considering',
  'Constellating',
  'Contemplating',
  'Counting',
  'Crossing',
  'Cuneiforming',
  'Damming',
  'Deciphering',
  'Deliberating',
  'Divining',
  'Drifting',
  'Dyeing',
  'Embossing',
  'Engilding',
  'Engraving',
  'Etching',
  'Faceting',
  'Filigreeing',
  'Firing',
  'Fishing',
  'Flooding',
  'Fording',
  'Forging',
  'Founding',
  'Gilding',
  'Glazing',
  'Gliding',
  'Goldsmithing',
  'Hammering',
  'Harvesting',
  'Impressing',
  'Incising',
  'Inlaying',
  'Inscribing',
  'Invoking',
  'Irrigating',
  'Kneading',
  'Leveling',
  'Libating',
  'Malting',
  'Mashoofing',
  'Measuring',
  'Milling',
  'Molding',
  'Mortaring',
  'Mudbricking',
  'Mulling',
  'Musing',
  'Paddling',
  'Petitioning',
  'Plotting',
  'Plowing',
  'Plying',
  'Poling',
  'Polishing',
  'Pondering',
  'Prophesying',
  'Punting',
  'Raising',
  'Reaping',
  'Reasoning',
  'Reckoning',
  'Reflecting',
  'Riveting',
  'Rolling',
  'Rowing',
  'Ruminating',
  'Scribing',
  'Sealing',
  'Shaping',
  'Sluicing',
  'Smelting',
  'Smithing',
  'Soldering',
  'Sowing',
  'Spinning',
  'Stacking',
  'Stamping',
  'Stargazing',
  'Summoning',
  'Surveying',
  'Tallying',
  'Tempering',
  'Terracing',
  'Threading',
  'Threshing',
  'Throwing',
  'Trading',
  'Transcribing',
  'Ur-building',
  'Vaulting',
  'Wading',
  'Watering',
  'Weaving',
  'Wedging',
  'Weighing',
  'Winnowing',
  'Ziggurating',
]
